;;; For Capstone Engine. AUTO-GENERATED FILE, DO NOT EDIT [sparc-const.el]

;; Enums corresponding to Sparc condition codes, both icc's and fcc's.

(defconst capstone-SPARC_CC_INVALID 0)

;; Integer condition codes
(defconst capstone-SPARC_CC_ICC_A (+ 8 256))
(defconst capstone-SPARC_CC_ICC_N (+ 0 256))
(defconst capstone-SPARC_CC_ICC_NE (+ 9 256))
(defconst capstone-SPARC_CC_ICC_E (+ 1 256))
(defconst capstone-SPARC_CC_ICC_G (+ 10 256))
(defconst capstone-SPARC_CC_ICC_LE (+ 2 256))
(defconst capstone-SPARC_CC_ICC_GE (+ 11 256))
(defconst capstone-SPARC_CC_ICC_L (+ 3 256))
(defconst capstone-SPARC_CC_ICC_GU (+ 12 256))
(defconst capstone-SPARC_CC_ICC_LEU (+ 4 256))
(defconst capstone-SPARC_CC_ICC_CC (+ 13 256))
(defconst capstone-SPARC_CC_ICC_CS (+ 5 256))
(defconst capstone-SPARC_CC_ICC_POS (+ 14 256))
(defconst capstone-SPARC_CC_ICC_NEG (+ 6 256))
(defconst capstone-SPARC_CC_ICC_VC (+ 15 256))
(defconst capstone-SPARC_CC_ICC_VS (+ 7 256))

;; Floating condition codes
(defconst capstone-SPARC_CC_FCC_A (+ 8 16 256))
(defconst capstone-SPARC_CC_FCC_N (+ 0 16 256))
(defconst capstone-SPARC_CC_FCC_U (+ 7 16 256))
(defconst capstone-SPARC_CC_FCC_G (+ 6 16 256))
(defconst capstone-SPARC_CC_FCC_UG (+ 5 16 256))
(defconst capstone-SPARC_CC_FCC_L (+ 4 16 256))
(defconst capstone-SPARC_CC_FCC_UL (+ 3 16 256))
(defconst capstone-SPARC_CC_FCC_LG (+ 2 16 256))
(defconst capstone-SPARC_CC_FCC_NE (+ 1 16 256))
(defconst capstone-SPARC_CC_FCC_E (+ 9 16 256))
(defconst capstone-SPARC_CC_FCC_UE (+ 10 16 256))
(defconst capstone-SPARC_CC_FCC_GE (+ 11 16 256))
(defconst capstone-SPARC_CC_FCC_UGE (+ 12 16 256))
(defconst capstone-SPARC_CC_FCC_LE (+ 13 16 256))
(defconst capstone-SPARC_CC_FCC_ULE (+ 14 16 256))
(defconst capstone-SPARC_CC_FCC_O (+ 15 16 256))

;; Branch hint

(defconst capstone-SPARC_HINT_INVALID 0)
(defconst capstone-SPARC_HINT_A (lsh 1 0))
(defconst capstone-SPARC_HINT_PT (lsh 1 1))
(defconst capstone-SPARC_HINT_PN (lsh 1 2))

;; Operand type for instruction's operands

(defconst capstone-SPARC_OP_INVALID 0)
(defconst capstone-SPARC_OP_REG 1)
(defconst capstone-SPARC_OP_IMM 2)
(defconst capstone-SPARC_OP_MEM 3)

;; SPARC registers

(defconst capstone-SPARC_REG_INVALID 0)
(defconst capstone-SPARC_REG_F0 1)
(defconst capstone-SPARC_REG_F1 2)
(defconst capstone-SPARC_REG_F2 3)
(defconst capstone-SPARC_REG_F3 4)
(defconst capstone-SPARC_REG_F4 5)
(defconst capstone-SPARC_REG_F5 6)
(defconst capstone-SPARC_REG_F6 7)
(defconst capstone-SPARC_REG_F7 8)
(defconst capstone-SPARC_REG_F8 9)
(defconst capstone-SPARC_REG_F9 10)
(defconst capstone-SPARC_REG_F10 11)
(defconst capstone-SPARC_REG_F11 12)
(defconst capstone-SPARC_REG_F12 13)
(defconst capstone-SPARC_REG_F13 14)
(defconst capstone-SPARC_REG_F14 15)
(defconst capstone-SPARC_REG_F15 16)
(defconst capstone-SPARC_REG_F16 17)
(defconst capstone-SPARC_REG_F17 18)
(defconst capstone-SPARC_REG_F18 19)
(defconst capstone-SPARC_REG_F19 20)
(defconst capstone-SPARC_REG_F20 21)
(defconst capstone-SPARC_REG_F21 22)
(defconst capstone-SPARC_REG_F22 23)
(defconst capstone-SPARC_REG_F23 24)
(defconst capstone-SPARC_REG_F24 25)
(defconst capstone-SPARC_REG_F25 26)
(defconst capstone-SPARC_REG_F26 27)
(defconst capstone-SPARC_REG_F27 28)
(defconst capstone-SPARC_REG_F28 29)
(defconst capstone-SPARC_REG_F29 30)
(defconst capstone-SPARC_REG_F30 31)
(defconst capstone-SPARC_REG_F31 32)
(defconst capstone-SPARC_REG_F32 33)
(defconst capstone-SPARC_REG_F34 34)
(defconst capstone-SPARC_REG_F36 35)
(defconst capstone-SPARC_REG_F38 36)
(defconst capstone-SPARC_REG_F40 37)
(defconst capstone-SPARC_REG_F42 38)
(defconst capstone-SPARC_REG_F44 39)
(defconst capstone-SPARC_REG_F46 40)
(defconst capstone-SPARC_REG_F48 41)
(defconst capstone-SPARC_REG_F50 42)
(defconst capstone-SPARC_REG_F52 43)
(defconst capstone-SPARC_REG_F54 44)
(defconst capstone-SPARC_REG_F56 45)
(defconst capstone-SPARC_REG_F58 46)
(defconst capstone-SPARC_REG_F60 47)
(defconst capstone-SPARC_REG_F62 48)
(defconst capstone-SPARC_REG_FCC0 49)
(defconst capstone-SPARC_REG_FCC1 50)
(defconst capstone-SPARC_REG_FCC2 51)
(defconst capstone-SPARC_REG_FCC3 52)
(defconst capstone-SPARC_REG_FP 53)
(defconst capstone-SPARC_REG_G0 54)
(defconst capstone-SPARC_REG_G1 55)
(defconst capstone-SPARC_REG_G2 56)
(defconst capstone-SPARC_REG_G3 57)
(defconst capstone-SPARC_REG_G4 58)
(defconst capstone-SPARC_REG_G5 59)
(defconst capstone-SPARC_REG_G6 60)
(defconst capstone-SPARC_REG_G7 61)
(defconst capstone-SPARC_REG_I0 62)
(defconst capstone-SPARC_REG_I1 63)
(defconst capstone-SPARC_REG_I2 64)
(defconst capstone-SPARC_REG_I3 65)
(defconst capstone-SPARC_REG_I4 66)
(defconst capstone-SPARC_REG_I5 67)
(defconst capstone-SPARC_REG_I7 68)
(defconst capstone-SPARC_REG_ICC 69)
(defconst capstone-SPARC_REG_L0 70)
(defconst capstone-SPARC_REG_L1 71)
(defconst capstone-SPARC_REG_L2 72)
(defconst capstone-SPARC_REG_L3 73)
(defconst capstone-SPARC_REG_L4 74)
(defconst capstone-SPARC_REG_L5 75)
(defconst capstone-SPARC_REG_L6 76)
(defconst capstone-SPARC_REG_L7 77)
(defconst capstone-SPARC_REG_O0 78)
(defconst capstone-SPARC_REG_O1 79)
(defconst capstone-SPARC_REG_O2 80)
(defconst capstone-SPARC_REG_O3 81)
(defconst capstone-SPARC_REG_O4 82)
(defconst capstone-SPARC_REG_O5 83)
(defconst capstone-SPARC_REG_O7 84)
(defconst capstone-SPARC_REG_SP 85)
(defconst capstone-SPARC_REG_Y 86)
(defconst capstone-SPARC_REG_XCC 87)
(defconst capstone-SPARC_REG_ENDING 88)
(defconst capstone-SPARC_REG_O6 capstone-SPARC_REG_SP)
(defconst capstone-SPARC_REG_I6 capstone-SPARC_REG_FP)

;; SPARC instruction

(defconst capstone-SPARC_INS_INVALID 0)
(defconst capstone-SPARC_INS_ADDCC 1)
(defconst capstone-SPARC_INS_ADDX 2)
(defconst capstone-SPARC_INS_ADDXCC 3)
(defconst capstone-SPARC_INS_ADDXC 4)
(defconst capstone-SPARC_INS_ADDXCCC 5)
(defconst capstone-SPARC_INS_ADD 6)
(defconst capstone-SPARC_INS_ALIGNADDR 7)
(defconst capstone-SPARC_INS_ALIGNADDRL 8)
(defconst capstone-SPARC_INS_ANDCC 9)
(defconst capstone-SPARC_INS_ANDNCC 10)
(defconst capstone-SPARC_INS_ANDN 11)
(defconst capstone-SPARC_INS_AND 12)
(defconst capstone-SPARC_INS_ARRAY16 13)
(defconst capstone-SPARC_INS_ARRAY32 14)
(defconst capstone-SPARC_INS_ARRAY8 15)
(defconst capstone-SPARC_INS_B 16)
(defconst capstone-SPARC_INS_JMP 17)
(defconst capstone-SPARC_INS_BMASK 18)
(defconst capstone-SPARC_INS_FB 19)
(defconst capstone-SPARC_INS_BRGEZ 20)
(defconst capstone-SPARC_INS_BRGZ 21)
(defconst capstone-SPARC_INS_BRLEZ 22)
(defconst capstone-SPARC_INS_BRLZ 23)
(defconst capstone-SPARC_INS_BRNZ 24)
(defconst capstone-SPARC_INS_BRZ 25)
(defconst capstone-SPARC_INS_BSHUFFLE 26)
(defconst capstone-SPARC_INS_CALL 27)
(defconst capstone-SPARC_INS_CASX 28)
(defconst capstone-SPARC_INS_CAS 29)
(defconst capstone-SPARC_INS_CMASK16 30)
(defconst capstone-SPARC_INS_CMASK32 31)
(defconst capstone-SPARC_INS_CMASK8 32)
(defconst capstone-SPARC_INS_CMP 33)
(defconst capstone-SPARC_INS_EDGE16 34)
(defconst capstone-SPARC_INS_EDGE16L 35)
(defconst capstone-SPARC_INS_EDGE16LN 36)
(defconst capstone-SPARC_INS_EDGE16N 37)
(defconst capstone-SPARC_INS_EDGE32 38)
(defconst capstone-SPARC_INS_EDGE32L 39)
(defconst capstone-SPARC_INS_EDGE32LN 40)
(defconst capstone-SPARC_INS_EDGE32N 41)
(defconst capstone-SPARC_INS_EDGE8 42)
(defconst capstone-SPARC_INS_EDGE8L 43)
(defconst capstone-SPARC_INS_EDGE8LN 44)
(defconst capstone-SPARC_INS_EDGE8N 45)
(defconst capstone-SPARC_INS_FABSD 46)
(defconst capstone-SPARC_INS_FABSQ 47)
(defconst capstone-SPARC_INS_FABSS 48)
(defconst capstone-SPARC_INS_FADDD 49)
(defconst capstone-SPARC_INS_FADDQ 50)
(defconst capstone-SPARC_INS_FADDS 51)
(defconst capstone-SPARC_INS_FALIGNDATA 52)
(defconst capstone-SPARC_INS_FAND 53)
(defconst capstone-SPARC_INS_FANDNOT1 54)
(defconst capstone-SPARC_INS_FANDNOT1S 55)
(defconst capstone-SPARC_INS_FANDNOT2 56)
(defconst capstone-SPARC_INS_FANDNOT2S 57)
(defconst capstone-SPARC_INS_FANDS 58)
(defconst capstone-SPARC_INS_FCHKSM16 59)
(defconst capstone-SPARC_INS_FCMPD 60)
(defconst capstone-SPARC_INS_FCMPEQ16 61)
(defconst capstone-SPARC_INS_FCMPEQ32 62)
(defconst capstone-SPARC_INS_FCMPGT16 63)
(defconst capstone-SPARC_INS_FCMPGT32 64)
(defconst capstone-SPARC_INS_FCMPLE16 65)
(defconst capstone-SPARC_INS_FCMPLE32 66)
(defconst capstone-SPARC_INS_FCMPNE16 67)
(defconst capstone-SPARC_INS_FCMPNE32 68)
(defconst capstone-SPARC_INS_FCMPQ 69)
(defconst capstone-SPARC_INS_FCMPS 70)
(defconst capstone-SPARC_INS_FDIVD 71)
(defconst capstone-SPARC_INS_FDIVQ 72)
(defconst capstone-SPARC_INS_FDIVS 73)
(defconst capstone-SPARC_INS_FDMULQ 74)
(defconst capstone-SPARC_INS_FDTOI 75)
(defconst capstone-SPARC_INS_FDTOQ 76)
(defconst capstone-SPARC_INS_FDTOS 77)
(defconst capstone-SPARC_INS_FDTOX 78)
(defconst capstone-SPARC_INS_FEXPAND 79)
(defconst capstone-SPARC_INS_FHADDD 80)
(defconst capstone-SPARC_INS_FHADDS 81)
(defconst capstone-SPARC_INS_FHSUBD 82)
(defconst capstone-SPARC_INS_FHSUBS 83)
(defconst capstone-SPARC_INS_FITOD 84)
(defconst capstone-SPARC_INS_FITOQ 85)
(defconst capstone-SPARC_INS_FITOS 86)
(defconst capstone-SPARC_INS_FLCMPD 87)
(defconst capstone-SPARC_INS_FLCMPS 88)
(defconst capstone-SPARC_INS_FLUSHW 89)
(defconst capstone-SPARC_INS_FMEAN16 90)
(defconst capstone-SPARC_INS_FMOVD 91)
(defconst capstone-SPARC_INS_FMOVQ 92)
(defconst capstone-SPARC_INS_FMOVRDGEZ 93)
(defconst capstone-SPARC_INS_FMOVRQGEZ 94)
(defconst capstone-SPARC_INS_FMOVRSGEZ 95)
(defconst capstone-SPARC_INS_FMOVRDGZ 96)
(defconst capstone-SPARC_INS_FMOVRQGZ 97)
(defconst capstone-SPARC_INS_FMOVRSGZ 98)
(defconst capstone-SPARC_INS_FMOVRDLEZ 99)
(defconst capstone-SPARC_INS_FMOVRQLEZ 100)
(defconst capstone-SPARC_INS_FMOVRSLEZ 101)
(defconst capstone-SPARC_INS_FMOVRDLZ 102)
(defconst capstone-SPARC_INS_FMOVRQLZ 103)
(defconst capstone-SPARC_INS_FMOVRSLZ 104)
(defconst capstone-SPARC_INS_FMOVRDNZ 105)
(defconst capstone-SPARC_INS_FMOVRQNZ 106)
(defconst capstone-SPARC_INS_FMOVRSNZ 107)
(defconst capstone-SPARC_INS_FMOVRDZ 108)
(defconst capstone-SPARC_INS_FMOVRQZ 109)
(defconst capstone-SPARC_INS_FMOVRSZ 110)
(defconst capstone-SPARC_INS_FMOVS 111)
(defconst capstone-SPARC_INS_FMUL8SUX16 112)
(defconst capstone-SPARC_INS_FMUL8ULX16 113)
(defconst capstone-SPARC_INS_FMUL8X16 114)
(defconst capstone-SPARC_INS_FMUL8X16AL 115)
(defconst capstone-SPARC_INS_FMUL8X16AU 116)
(defconst capstone-SPARC_INS_FMULD 117)
(defconst capstone-SPARC_INS_FMULD8SUX16 118)
(defconst capstone-SPARC_INS_FMULD8ULX16 119)
(defconst capstone-SPARC_INS_FMULQ 120)
(defconst capstone-SPARC_INS_FMULS 121)
(defconst capstone-SPARC_INS_FNADDD 122)
(defconst capstone-SPARC_INS_FNADDS 123)
(defconst capstone-SPARC_INS_FNAND 124)
(defconst capstone-SPARC_INS_FNANDS 125)
(defconst capstone-SPARC_INS_FNEGD 126)
(defconst capstone-SPARC_INS_FNEGQ 127)
(defconst capstone-SPARC_INS_FNEGS 128)
(defconst capstone-SPARC_INS_FNHADDD 129)
(defconst capstone-SPARC_INS_FNHADDS 130)
(defconst capstone-SPARC_INS_FNOR 131)
(defconst capstone-SPARC_INS_FNORS 132)
(defconst capstone-SPARC_INS_FNOT1 133)
(defconst capstone-SPARC_INS_FNOT1S 134)
(defconst capstone-SPARC_INS_FNOT2 135)
(defconst capstone-SPARC_INS_FNOT2S 136)
(defconst capstone-SPARC_INS_FONE 137)
(defconst capstone-SPARC_INS_FONES 138)
(defconst capstone-SPARC_INS_FOR 139)
(defconst capstone-SPARC_INS_FORNOT1 140)
(defconst capstone-SPARC_INS_FORNOT1S 141)
(defconst capstone-SPARC_INS_FORNOT2 142)
(defconst capstone-SPARC_INS_FORNOT2S 143)
(defconst capstone-SPARC_INS_FORS 144)
(defconst capstone-SPARC_INS_FPACK16 145)
(defconst capstone-SPARC_INS_FPACK32 146)
(defconst capstone-SPARC_INS_FPACKFIX 147)
(defconst capstone-SPARC_INS_FPADD16 148)
(defconst capstone-SPARC_INS_FPADD16S 149)
(defconst capstone-SPARC_INS_FPADD32 150)
(defconst capstone-SPARC_INS_FPADD32S 151)
(defconst capstone-SPARC_INS_FPADD64 152)
(defconst capstone-SPARC_INS_FPMERGE 153)
(defconst capstone-SPARC_INS_FPSUB16 154)
(defconst capstone-SPARC_INS_FPSUB16S 155)
(defconst capstone-SPARC_INS_FPSUB32 156)
(defconst capstone-SPARC_INS_FPSUB32S 157)
(defconst capstone-SPARC_INS_FQTOD 158)
(defconst capstone-SPARC_INS_FQTOI 159)
(defconst capstone-SPARC_INS_FQTOS 160)
(defconst capstone-SPARC_INS_FQTOX 161)
(defconst capstone-SPARC_INS_FSLAS16 162)
(defconst capstone-SPARC_INS_FSLAS32 163)
(defconst capstone-SPARC_INS_FSLL16 164)
(defconst capstone-SPARC_INS_FSLL32 165)
(defconst capstone-SPARC_INS_FSMULD 166)
(defconst capstone-SPARC_INS_FSQRTD 167)
(defconst capstone-SPARC_INS_FSQRTQ 168)
(defconst capstone-SPARC_INS_FSQRTS 169)
(defconst capstone-SPARC_INS_FSRA16 170)
(defconst capstone-SPARC_INS_FSRA32 171)
(defconst capstone-SPARC_INS_FSRC1 172)
(defconst capstone-SPARC_INS_FSRC1S 173)
(defconst capstone-SPARC_INS_FSRC2 174)
(defconst capstone-SPARC_INS_FSRC2S 175)
(defconst capstone-SPARC_INS_FSRL16 176)
(defconst capstone-SPARC_INS_FSRL32 177)
(defconst capstone-SPARC_INS_FSTOD 178)
(defconst capstone-SPARC_INS_FSTOI 179)
(defconst capstone-SPARC_INS_FSTOQ 180)
(defconst capstone-SPARC_INS_FSTOX 181)
(defconst capstone-SPARC_INS_FSUBD 182)
(defconst capstone-SPARC_INS_FSUBQ 183)
(defconst capstone-SPARC_INS_FSUBS 184)
(defconst capstone-SPARC_INS_FXNOR 185)
(defconst capstone-SPARC_INS_FXNORS 186)
(defconst capstone-SPARC_INS_FXOR 187)
(defconst capstone-SPARC_INS_FXORS 188)
(defconst capstone-SPARC_INS_FXTOD 189)
(defconst capstone-SPARC_INS_FXTOQ 190)
(defconst capstone-SPARC_INS_FXTOS 191)
(defconst capstone-SPARC_INS_FZERO 192)
(defconst capstone-SPARC_INS_FZEROS 193)
(defconst capstone-SPARC_INS_JMPL 194)
(defconst capstone-SPARC_INS_LDD 195)
(defconst capstone-SPARC_INS_LD 196)
(defconst capstone-SPARC_INS_LDQ 197)
(defconst capstone-SPARC_INS_LDSB 198)
(defconst capstone-SPARC_INS_LDSH 199)
(defconst capstone-SPARC_INS_LDSW 200)
(defconst capstone-SPARC_INS_LDUB 201)
(defconst capstone-SPARC_INS_LDUH 202)
(defconst capstone-SPARC_INS_LDX 203)
(defconst capstone-SPARC_INS_LZCNT 204)
(defconst capstone-SPARC_INS_MEMBAR 205)
(defconst capstone-SPARC_INS_MOVDTOX 206)
(defconst capstone-SPARC_INS_MOV 207)
(defconst capstone-SPARC_INS_MOVRGEZ 208)
(defconst capstone-SPARC_INS_MOVRGZ 209)
(defconst capstone-SPARC_INS_MOVRLEZ 210)
(defconst capstone-SPARC_INS_MOVRLZ 211)
(defconst capstone-SPARC_INS_MOVRNZ 212)
(defconst capstone-SPARC_INS_MOVRZ 213)
(defconst capstone-SPARC_INS_MOVSTOSW 214)
(defconst capstone-SPARC_INS_MOVSTOUW 215)
(defconst capstone-SPARC_INS_MULX 216)
(defconst capstone-SPARC_INS_NOP 217)
(defconst capstone-SPARC_INS_ORCC 218)
(defconst capstone-SPARC_INS_ORNCC 219)
(defconst capstone-SPARC_INS_ORN 220)
(defconst capstone-SPARC_INS_OR 221)
(defconst capstone-SPARC_INS_PDIST 222)
(defconst capstone-SPARC_INS_PDISTN 223)
(defconst capstone-SPARC_INS_POPC 224)
(defconst capstone-SPARC_INS_RD 225)
(defconst capstone-SPARC_INS_RESTORE 226)
(defconst capstone-SPARC_INS_RETT 227)
(defconst capstone-SPARC_INS_SAVE 228)
(defconst capstone-SPARC_INS_SDIVCC 229)
(defconst capstone-SPARC_INS_SDIVX 230)
(defconst capstone-SPARC_INS_SDIV 231)
(defconst capstone-SPARC_INS_SETHI 232)
(defconst capstone-SPARC_INS_SHUTDOWN 233)
(defconst capstone-SPARC_INS_SIAM 234)
(defconst capstone-SPARC_INS_SLLX 235)
(defconst capstone-SPARC_INS_SLL 236)
(defconst capstone-SPARC_INS_SMULCC 237)
(defconst capstone-SPARC_INS_SMUL 238)
(defconst capstone-SPARC_INS_SRAX 239)
(defconst capstone-SPARC_INS_SRA 240)
(defconst capstone-SPARC_INS_SRLX 241)
(defconst capstone-SPARC_INS_SRL 242)
(defconst capstone-SPARC_INS_STBAR 243)
(defconst capstone-SPARC_INS_STB 244)
(defconst capstone-SPARC_INS_STD 245)
(defconst capstone-SPARC_INS_ST 246)
(defconst capstone-SPARC_INS_STH 247)
(defconst capstone-SPARC_INS_STQ 248)
(defconst capstone-SPARC_INS_STX 249)
(defconst capstone-SPARC_INS_SUBCC 250)
(defconst capstone-SPARC_INS_SUBX 251)
(defconst capstone-SPARC_INS_SUBXCC 252)
(defconst capstone-SPARC_INS_SUB 253)
(defconst capstone-SPARC_INS_SWAP 254)
(defconst capstone-SPARC_INS_TADDCCTV 255)
(defconst capstone-SPARC_INS_TADDCC 256)
(defconst capstone-SPARC_INS_T 257)
(defconst capstone-SPARC_INS_TSUBCCTV 258)
(defconst capstone-SPARC_INS_TSUBCC 259)
(defconst capstone-SPARC_INS_UDIVCC 260)
(defconst capstone-SPARC_INS_UDIVX 261)
(defconst capstone-SPARC_INS_UDIV 262)
(defconst capstone-SPARC_INS_UMULCC 263)
(defconst capstone-SPARC_INS_UMULXHI 264)
(defconst capstone-SPARC_INS_UMUL 265)
(defconst capstone-SPARC_INS_UNIMP 266)
(defconst capstone-SPARC_INS_FCMPED 267)
(defconst capstone-SPARC_INS_FCMPEQ 268)
(defconst capstone-SPARC_INS_FCMPES 269)
(defconst capstone-SPARC_INS_WR 270)
(defconst capstone-SPARC_INS_XMULX 271)
(defconst capstone-SPARC_INS_XMULXHI 272)
(defconst capstone-SPARC_INS_XNORCC 273)
(defconst capstone-SPARC_INS_XNOR 274)
(defconst capstone-SPARC_INS_XORCC 275)
(defconst capstone-SPARC_INS_XOR 276)
(defconst capstone-SPARC_INS_RET 277)
(defconst capstone-SPARC_INS_RETL 278)
(defconst capstone-SPARC_INS_ENDING 279)

;; Group of SPARC instructions

(defconst capstone-SPARC_GRP_INVALID 0)

;; Generic groups
(defconst capstone-SPARC_GRP_JUMP 1)

;; Architecture-specific groups
(defconst capstone-SPARC_GRP_HARDQUAD 128)
(defconst capstone-SPARC_GRP_V9 129)
(defconst capstone-SPARC_GRP_VIS 130)
(defconst capstone-SPARC_GRP_VIS2 131)
(defconst capstone-SPARC_GRP_VIS3 132)
(defconst capstone-SPARC_GRP_32BIT 133)
(defconst capstone-SPARC_GRP_64BIT 134)
(defconst capstone-SPARC_GRP_ENDING 135)

(provide 'capstone-sparc-const)
